### ISSUE TITLE
Vulnerabilities in org.jbos.logging dependency - can a more secure alternative be used?

### ISSUE THREAD

**Issue by jahveen** [looorent/keycloak-configurable-token-api#12]
https://github.com/looorent/keycloak-configurable-token-api/blob/b01fd2339c0325bd3167b13bb65861f929176c85/build.gradle#L25

Vulnerabilities listed in https://mvnrepository.com/artifact/org.jboss.logging/jboss-logging

**Comment by looorent** [comment]
This logging library is the one used by Keycloak itself. The exact version and implementation is provided by Keycloak (see `compileOnly`). It would not be appropriate to add another one.
