### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by roxspring** [looorent/keycloak-configurable-token-api#2]
Hi,

This looks like it might be useful for an upcoming project, but I don't see any licensing terms anywhere.

How about adding a LICENSE file:
https://github.com/looorent/keycloak-configurable-token-api/community/license/new?branch=master

(Apache 2.0 or MIT would be my preference)

**Comment by looorent** [comment]
Hello,

You are right, I forgot it. Thanks for your feedback.
I've just pushed the MIT license.
