### ISSUE TITLE
why not checking the role against the scope in the token?

### ISSUE THREAD

**Issue by chicco785** [looorent/keycloak-configurable-token-api#3]
i think it would be more clean checking the role against the scope (which is by default returned, while realm access is not), what do you think?

https://github.com/looorent/keycloak-configurable-token-api/blob/da80a09e674845fa8d81c6802f1917f2591fc6d4/src/main/java/be/looorent/ConfigurableTokenResourceProvider.java#L110

**Comment by looorent** [comment]
Hi @chicco785,

Thanks for this feedback.

One year later (sorry about that), version `1.1.0` now uses information from the user model (not the token's payload). However, this does not use the scope yet. I believe (correct me if I'm wrong) this is not possible to assign a scope to a single user, which is very important to prevent someone to request long-lived tokens without being granted for it.
