### ISSUE TITLE
the createToken method is not checking that the token is valid before attempting to token creation

### ISSUE THREAD

**Issue by chicco785** [looorent/keycloak-configurable-token-api#4]
https://github.com/looorent/keycloak-configurable-token-api/blob/17ff04ac0d1b14fe1f261bc645f7f3e25e23e217/src/main/java/be/looorent/ConfigurableTokenResourceProvider.java#L62

this results in 500 errors when the token is not active, while it would be better to get some proper error message (e.g. active = false, as introspection does)

**Comment by looorent** [comment]
Hi @chicco785,

Thanks for this feedback.

One year later (sorry about that, again), version `1.1.0` now verifies the token before making any assumption (exactly with the same principle than `/introspection`). It also checks session's validity.

Therefore you will get more feedback when a call fails.
