### ISSUE TITLE
shouldn't be also the session updated?

### ISSUE THREAD

**Issue by chicco785** [looorent/keycloak-configurable-token-api#5]
I haven't yet tested, but looking at the code I suspect session get invalidated when they reached their max lifespan, this implies token are not valid anymore, regardless the expiration date they may have. (being an issue then also for short live token, because you are not actually removing the session).
In the session the only value that is stored AFAIK, it's the start time. Probably fixing the start time in the future (or in the past for short lived token) will solve the issue. But it's just a guess.

https://github.com/looorent/keycloak-configurable-token-api/blob/17ff04ac0d1b14fe1f261bc645f7f3e25e23e217/src/main/java/be/looorent/ConfigurableTokenResourceProvider.java#L71

**Comment by looorent** [comment]
Hi @chicco785,

Thanks for this feedback.

One year later (sorry about that, again), version `1.1.0` now updates the session activity (like `/introspection` does). 
On the other hand, the original session expiration is not affected by this call considering the generated access token only receives a different expiration date.
