### ISSUE TITLE
Status 500 when request token

### ISSUE THREAD

**Issue by maykon** [looorent/keycloak-configurable-token-api#6]
When I request a token I receive status 500 code and internal page error? What's wrong?

![image](https://user-images.githubusercontent.com/14884/83565229-6dd6f180-a4f4-11ea-81e9-76633976f778.png)

**Comment by maykon** [comment]
Use this token pass to bearer authentication header

![image](https://user-images.githubusercontent.com/14884/83565329-9bbc3600-a4f4-11ea-8571-c95388fd2084.png)

**Comment by looorent** [comment]
Could you show Keycloak's logs?
You can also use version `1.1.0` of this library, which will give you more feedback about the error.
