### ISSUE TITLE
 Failed to parse JWT

### ISSUE THREAD

**Issue by verbeckii** [looorent/keycloak-configurable-token-api#8]
Hello

I'm trying to test
When I type 

`curl -X POST -d '{ "tokenLifespanInSeconds": 63113904}' -H "Content-Type: application/json" -H "Authorization: Bearer <user-access-token>" https://mydomain/auth/realms/master/configurable-token`

Got this:

`{"errorMessage":"access_token_introspection_failed: Failed to parse JWT"}`

I'm use keycloak-configurable-token-1.2.0.jar and keycloak-configurable-token-1.1.0.jar

What I did wrong?

**Comment by looorent** [comment]
Hi @sxenny,

We are running these two versions without any issue.

I've tried your curl command on Keycloak 12 (with keycloak-configurable-token-1.3.0.jar) and I cannot reproduce your error.

What kind of token do you provide to the Authorization Header? It expects a valid JWT **_access_** token (not an ID Token or a refresh token).
Could you also provide keycloak's logs?
