### ISSUE TITLE
Revoking a longline token

### ISSUE THREAD

**Issue by jonf-78** [looorent/keycloak-configurable-token-api#9]
Hi,

Thanks for publishing this It fits our use are perfectly. Have a question, apologies if it is basic :) and my mis-understanding.

Once we have issues a long-life token to the user is there a way to revoke/invalidate that token that has been issued within Keycloak ?

Thanks
Jon

**Comment by looorent** [comment]
Hi @jonf-78 ,

Thanks for your feedback.

JWTs are designed to be decentralized. Most of the time, only their signature is validated (without interrogating the IDP). Therefore this question is more about how your service/middleware validates the token:
* If it only validates its signature, there is no way to check whether the Keycloak user behind it is valid or not;
* You still can interrogate Keycloak to check whether the user associated to this token is valid or nor (by calling `https://${keycloakHost}:${keycloakPort}/auth/realms/${realmName}/protocol/openid-connect/userinfo`, for instance). But this requires an extra step, that forces your architecture to be dependent on the IDP.
